### ISSUE TITLE
Your TypeScript version is invalid

### ISSUE THREAD

**Issue by nampdn** [Quramy/tsuquyomi#106]
Hi, I just give this plugin a try and can't get it work in Typescript 1.7.5, 2.0, 2.1.4
What can I do?
>>[Tsuquyomi] Your TypeScript version is invalid. module.js:474^@    throw err;^@    ^^@^@Error: Cannot find module 'C:\@Projects\@mdds\@vgmeducation\vgm.education.discuss^@ode_modules'^@    at Function.Module._resolveFilename (module.js:472:15)^@    at Function.Module._load (module.js:420:25)^@    at Module.runMain (module.js:607:10)^@
at run (bootstrap_node.js:382:7)^@    at startup (bootstrap_node.js:137:9)^@    at bootstrap_node.js:497:3^@

**Comment by sheam** [comment]
I get this as well. The problem for me is when TypeScript is a dev dependancy in my package.json. If I edit a .ts file outside of a node project, I do not get this error, and it seems to use the globally installed version of typescript without error. But the project version and global version are 2.1.4.

**Comment by nampdn** [comment]
So, can I change the typescript version locally or wait for next update?

**Comment by sheam** [comment]
In the docs there is is a global variable yo can set, to force it to se the
global TS server. That fixed the problem for me.

**Comment by mattdsteele** [comment]
I'm seeing something similar. @nampdn did you get this resolved?

My environment:

* vim 8.0.69 (same with gvim, fyi)
* Windows 7 x64
* tsuquyomi and vimproc.vim installed latest versions via vim-plug
* typescript installed locally at version 2.1.5
* typescript also installed globally, version 2.1.5

As per the docs I've tried setting `g:tsuquyomi_use_dev_node_module` to both `0` and `1`, but get the same `Your TypeScript version is invalid` error as above. Same with uninstalling typescript locally and/or globally.

Nothing seems to fix (or even change) the error. Any ideas?

**Comment by nampdn** [comment]
@mattdsteele I still facing this problem :(

**Comment by AntonyGarand** [comment]
While I was also having this error, it was caused by my system to be unable to execute "tsc -v" with an absolute path or something. 

> Cannot find module 'path/to/project/node_modules' at Function.Module._resolveFilename (module.js:469:15)

I hotfixed it by replacing `"let out = s:Process.system(l:cmd.' --version')` with `let out = s:Process.system('tsc -v')` in `tsuquyomi/autoload/tsuquyomi/config.vim:114`, and it got back working as normal. 

This works using the global tsc server so it may not be a perfect solution for you. 
A hotfix to use the project version instead would be to use the following command instead:
`let out = s:Process.system('node ../../node_modules/typescript/bin/tsc -v')`
